"""add_price_history

Revision ID: 26b26ff41a73
Revises: 002
Create Date: 2026-03-28 10:42:58.339966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b26ff41a73'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_variant_id', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('median_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('min_price', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Integer(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_variant_id'], ['car_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_histories_car_variant_id'), 'price_histories', ['car_variant_id'], unique=False)
    op.drop_constraint('brands_name_key', 'brands', type_='unique')
    op.drop_index('ix_brands_name', table_name='brands')
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.drop_constraint('market_stats_car_variant_id_key', 'market_stats', type_='unique')
    op.drop_index('ix_market_stats_car_variant_id', table_name='market_stats')
    op.create_index(op.f('ix_market_stats_car_variant_id'), 'market_stats', ['car_variant_id'], unique=True)
    op.drop_constraint('segments_name_key', 'segments', type_='unique')
    op.drop_index('ix_segments_name', table_name='segments')
    op.create_index(op.f('ix_segments_name'), 'segments', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segments_name'), table_name='segments')
    op.create_index('ix_segments_name', 'segments', ['name'], unique=False)
    op.create_unique_constraint('segments_name_key', 'segments', ['name'])
    op.drop_index(op.f('ix_market_stats_car_variant_id'), table_name='market_stats')
    op.create_index('ix_market_stats_car_variant_id', 'market_stats', ['car_variant_id'], unique=False)
    op.create_unique_constraint('market_stats_car_variant_id_key', 'market_stats', ['car_variant_id'])
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.create_index('ix_brands_name', 'brands', ['name'], unique=False)
    op.create_unique_constraint('brands_name_key', 'brands', ['name'])
    op.drop_index(op.f('ix_price_histories_car_variant_id'), table_name='price_histories')
    op.drop_table('price_histories')
    # ### end Alembic commands ###
